engines:
    tslint:
        enabled: true
        channel: beta
        config: tslint.json
ratings:
    paths:
        - "**.ts"
exclude_paths:
    - src/test
    - src/main/font
    - src/main/pug
    - target
    - node_modules
