dist: trusty
sudo: required

language: node_js
node_js:
    - '7'

before_script:
    - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start

script:
    - 'npm run clean && npm run build && mkdir -p target/test && cp -R target/dist target/test/dist && npm run cover'

after_success:
    - 'cat ./target/reports/coverage/lcov.info | ./node_modules/.bin/coveralls -v'
